[package]
name = "procrastination"
version = "0.1.0"
authors = ["const"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term = "0.6"
rand = "0.7.3"
clap = "3.0.0-beta.1"
rustyline = "6.2.0"
